server:
  port: 8080

spring:
  application:
    name: hhplus-tdd-clean-architecture
  datasource:
    url: jdbc:h2:mem:hhplus-tdd-clean-architecture
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 1800000
      idle-timeout: 30000
      connection-timeout: 30000
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
      schema-locations: classpath:/schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      
      
      
      
      
      