-- users 테이블 생성
CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    name  VARCHAR(255)
);

-- lecture 테이블 생성
CREATE TABLE lecture
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(500) NOT NULL,
    instructor VARCHAR(255) NOT NULL
);

-- lecture_item 테이블 생성
CREATE TABLE lecture_item
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecture_id         BIGINT       NOT NULL,
    capacity           INTEGER      NOT NULL,
    remaining_capacity INTEGER      NOT NULL,
    lecture_time       TIMESTAMP(6) NOT NULL,
    FOREIGN KEY (lecture_id) REFERENCES lecture (id)
);

-- lecture_enrollment 테이블 생성
CREATE TABLE lecture_enrollment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrolled_at     TIMESTAMP(6) NOT NULL,
    lecture_id      BIGINT       NOT NULL,
    lecture_item_id BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    FOREIGN KEY (lecture_item_id) REFERENCES lecture_item (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- lecture_id와 user_id에 대한 유니크 제약 조건 추가
ALTER TABLE IF EXISTS recture_enrollment ADD CONSTRAINT unique_lecture_user UNIQUE (lecture_id, user_id);